import "./globals.css";
import { Poppins, Lato } from "next/font/google";

const poppins = Poppins({
  weight: ['100','200','300','400','500','600','700','800','900'],
  subsets: ["latin"],
  variable:'--font-poppins'
});

const lato = Lato({
  weight: ['100','300','400','700','900'],
  subsets: ["latin"],
  variable:'--font-lato'
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body className={poppins.variable}>{children}</body>
    </html>
  );
}
